cart/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('add-to-cart/', views.add_to_cart, name="add_to_cart"),
    path('delete-from-cart/', views.delete_cart_item, name="delete-from-cart"),
    path('update-cart/', views.update_cart_item, name="update-cart"),
    path('cart', views.cart_list, name="cart"),  
    path('checkout', views.checkout, name="checkout"),  

    path('checkout/payment/success', views.pay_success, name="pay-success"),   


    path('add-wishlist',views.add_wishlist, name='add_wishlist'),
    path('account/dashboard/wishlist',views.wishlist, name='wishlist'),

    path('delivery_price',views.delivery_price, name='delivery'),


] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls import handler400, handler403, handler404, handler500
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *


sitemaps = {
    'products':ProductSitemap,
    'cats': CategorySitemap,
    'vend': VendorSitemap,
    'subcats': SubCategorySitemap,
}


urlpatterns = [
    path('', views.home, name="home"),
    path('shop', views.shop, name="shop"),
    path('search', views.search, name="search"),

    path('shop/<str:title>-<int:cat_id>', views.category_product_list, name="category"),
    
    path('shop/<str:title>', views.subcat_product_list, name="subcat"),

    path('accounts/register', views.registerUser, name="register"),
    path('accounts/login/', views.loginView, name="login"),
    path('accounts/logout', views.logoutUser, name="logout"),
    path('accounts/dashboard', views.user_dash, name="user-dashboard"),
    path('contact-us', views.contact, name="contact"),
    path('about-us', views.about_us, name="about"),
    path('faq', views.faq, name="faq"),
    path('order-tracking', views.order_tracking, name="order-tracking"),

    path('accounts/forgot-password',views.forgot_password, name='forgot-password'),
    path('accounts/reset-password/<token>/',views.reset_password, name='reset-password'),
    path('accounts/change-password', views.change_password, name='change-password'),
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    
] 

handler404 = 'main.views.handler404'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/admin/admin/030/', admin.site.urls),
    path('', include('main.urls')),
    path('shop/', include('product.urls')),
    path('', include('cart.urls')),
    path('payment/', include('paystackpay.urls')),
    path('vendor/', include('vendor.urls')),

    path('www.excelcart.com.ng', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('www.excelcart.org', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('www.excelcart.com', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('www.excelcart.net', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('www.excelcart.shop', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('excelcart.shop', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('excelcart.com', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
]

main/models.py
from django.db import models
from django.utils.timezone import now
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from gdstorage.storage import GoogleDriveStorage

# Define Google Drive Storage
gd_storage = GoogleDriveStorage()

# Create your models here.

class Category(models.Model):
	title=models.CharField(max_length=60)
	image=models.ImageField(upload_to="category", storage=gd_storage)
	svg = models.FileField(upload_to="svg", null = True , blank= True, storage=gd_storage)

	class Meta:
		verbose_name_plural='Categories'

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" height="50" />'%(self.image.url))	

	def get_absolute_url(self):
            return f'/shop/{self.title}-{self.id}'	

	def __str__(self):
		return self.title

class SubCategory(models.Model):
	category = models.ForeignKey(Category,on_delete=models.CASCADE, null=True)
	svg = models.FileField(upload_to="svg",null = True,blank= True, storage=gd_storage)
	title=models.CharField(max_length=60)

	class Meta:
		verbose_name_plural='Sub Categories'

	def get_absolute_url(self):
		return f'/shop/{self.title}'		

	def __str__(self):
		return self.title

class Faq(models.Model):
	question = models.CharField(max_length=300)
	answer = RichTextField()

	def __str__(self):
		return self.question

class Contact(models.Model):
	email = models.EmailField()
	phone = models.IntegerField()
	message = models.CharField(max_length=500)

	def __str__(self):
		return self.email	

RATING=(
    ("1",'1 Star'),
    ("2",'2 Stars'),
    ("3",'3 Stars'),
    ("4",'4 Stars'),
    ("5",'5 Stars'),
)

class ExcelcartReview(models.Model):
	name=models.CharField(max_length=200)
	job = models.CharField(max_length=100)
	image = models.ImageField(upload_to="testimonials", null=True)
	title = models.CharField(max_length=200)	
	message = models.CharField(max_length=500)
	star =models.CharField(choices=RATING,max_length=150)
	def __str__(self):
		return self.name


class UserToken(models.Model):
	user= models.OneToOneField(User,on_delete=models.CASCADE)
	token = models.CharField(max_length=100)

	def __str__(self):
		return self.user.username


class Country(models.Model):
	name = models.CharField(max_length=200)

	class Meta:
		verbose_name_plural='Countries'

	def __str__(self):
		return self.name

class State(models.Model):
	name = models.CharField(max_length=200)
	country = models.ForeignKey(Country,on_delete=models.CASCADE)

	def __str__(self):
		return self.name

class City(models.Model):
	name = models.CharField(max_length=200)
	state = models.ForeignKey(State,on_delete=models.CASCADE, null=True)
	price = models.IntegerField(null=True, blank=True)

	class Meta:
		verbose_name_plural='Cities'

	def __str__(self):
		return self.name		

product/models.py
from django.db import models
from colorfield.fields import ColorField
from main.models import *
from vendor.models import *
from ckeditor.fields import RichTextField
from django.utils.timezone import now
from django.utils.html import mark_safe
import secrets
from gdstorage.storage import GoogleDriveStorage

# Define Google Drive Storage
gd_storage = GoogleDriveStorage()

# Create your models here.

stock_status =(
        ('1','In Stock'),
        ('2','Out Of Stock'),
        ('3','Pre-order'),
    )

class Product(models.Model):
        vendor = models.ForeignKey(Vendor,on_delete=models.CASCADE, null=True)
        name=models.CharField(max_length=200)
        thumb_nail = models.ImageField(upload_to="product_img/", null=True, storage=gd_storage)
        short = models.CharField(max_length=100, null=True)
        category=models.ForeignKey(Category,on_delete=models.CASCADE, null=True)
        sub_category=models.ForeignKey(SubCategory,on_delete=models.CASCADE, null=True)	
        color = models.CharField(max_length=100, null=True, blank=True)
        brand = models.CharField(max_length=100, null=True, blank=True)
        number=models.PositiveIntegerField(default=1, null=True, blank=True)
        ref=models.CharField(max_length=100, null=True, blank = True)
        description=models.TextField()
        date=models.DateTimeField(default=now)
        new=models.BooleanField(default=False)
        top_deals=models.BooleanField(default=False)
        sales = models.IntegerField(default=0)
        avg_ratings = models.IntegerField(default=0)
        topic_views = models.IntegerField(default=0)
        approve = models.BooleanField(default=False)

        class Meta:
                verbose_name_plural='Product'

        def __str__(self): 
            return self.name    

        def get_absolute_url(self):
            return f'/shop/{self.category}/{self.name}-{self.id}'    

        def save(self, *args, **kwargs) -> None: 
            if self.ref == None:       
                self.ref = secrets.token_urlsafe(7) 
                super().save(*args, **kwargs)  
            else:     
                super().save(*args, **kwargs)

class ProductImage(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    image = models.FileField(upload_to="product_img/", storage=gd_storage)

    class Meta:
        verbose_name_plural='Product Image'

    def __str__(self): 
        return self.product.name #

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))    

SIZE = [
        ("KG", "kilogramme", ),
        ("G", "gramme", ),
        ("XL", "extra-large", ),
    ]

class Variation(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    stock_status = models.CharField(choices=stock_status,default='In Stock',max_length=150)
    size_par = models.CharField(choices=SIZE,default='kilogramme',max_length=150, blank=True, null=True)
    size=models.CharField(max_length=100, null=True)
    price=models.PositiveIntegerField(default=0, null=True)
    dis_price=models.PositiveIntegerField(default=0, null=True, blank=True)
    discount=models.IntegerField(null=True, blank=True)

    class Meta:
    	verbose_name_plural='Variations'

    def __str__(self):
        return self.product.name

    def save(self, *args, **kwargs) -> None: 
        if self.dis_price == 0:
            super().save(*args, **kwargs)
        else:    
            discount = int(self.price) - int(self.dis_price)
            self.discount = discount * 100/int(self.price)
            super().save(*args, **kwargs) 

class ProductInformation(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    manufacturer=models.CharField(max_length=100, null=True, blank = True)
    ingredients = models.CharField(max_length=300, null=True, blank = True)
    package = models.CharField(max_length=300, null=True, blank=True)
    item_number=models.CharField(max_length=300, null=True, blank=True)
    prod_date=models.DateTimeField(default=now, editable=True, blank=True)
    expiry_date=models.DateTimeField(default=now, editable=True, blank=True)

    class Meta:
        verbose_name_plural='Product Info'

    def __str__(self):
        return self.product.name

class ProductCare(models.Model):
        product=models.ForeignKey(Product,on_delete=models.CASCADE)
        care = models.CharField(max_length=500, null=True)

        class Meta:
                verbose_name_plural='Product care'

        def __str__(self):
                return self.product.name


RATING=(
    ("1",'1 Star'),
    ("2",'2 Stars'),
    ("3",'3 Stars'),
    ("4",'4 Stars'),
    ("5",'5 Stars'),
)
class Review(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)    
    product = models.ForeignKey(Product,on_delete=models.CASCADE)   
    text=models.TextField()
    rating=models.IntegerField(choices=RATING,default=1)
    date=models.DateTimeField(default=now)

    class Meta:
        verbose_name_plural='Reviews'

    def get_review_rating(self):
        return self.product               

main/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django import forms
from .models import *
from cart.models import *


class SignupForm(UserCreationForm):
	password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'id': 'password1'}))
	
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["username"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"username",
			'id':"username",
			'placeholder':"Choose a username",
			'autocomplete': "username"

			})
		self.fields["email"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"email", 
			'name':"email",
			'id':"email",
			'placeholder':"Email",
			'autocomplete': "email"
			})
		self.fields["password1"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"password1",
			'id':"password1",
			'placeholder':"Password",
			'autocomplete': "password"
			})
		self.fields["password2"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"password2",
			'id':"password2",
			'placeholder':"Confirm Password",
			'autocomplete': "confirm-password"
			})


	class Meta:
		model=User
		fields=('email','username','password1','password2')


class AddressForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["address"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"address",
			'id':"address",
			'placeholder':"Enter Address",
			'rows': 4,
			})
		self.fields["phone"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"number", 
			'name':"phone",
			'id':"phone",
			'placeholder':"Enter Phone Number"
			})
		self.fields["name"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"name",
			'id':"name",
			'placeholder':"Enter the name of place"
			})

	class Meta:
		model= CustomerAddress
		fields=('address','phone','name')

main/templates/popupview/quickview.html
{% load static %}
 <!-- Quick View Modal Box Start -->
 {% for i in products %}
    <div class="modal fade theme-modal view-modal" id="view{{i.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl modal-fullscreen-sm-down">
            <div class="modal-content">
                <div class="modal-header p-0">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <i class="fa-solid fa-xmark"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row g-sm-4 g-2">
                        <div class="col-lg-6">
                            <div class="slider-image">
                                <img src="{{i.thumb_nail.url}}" class="img-fluid blur-up lazyloaded" alt="">
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="right-sidebar-modal">
                                <h4 class="title-name">{{i.name}}</h4>
                                {% if i.variation_set.first.discount %}
                                <h4 class="price">&#8358;{{i.variation_set.first.dis_price|floatformat:2}}</h4>
                                {% else %}
                                <h4 class="price">&#8358;{{i.variation_set.first.price|floatformat:2}}</h4>
                                {% endif %}
                                <div class="product-rating">
                                    <span class="ms-2">{{i.review_set.all.count}} Customer Reviews</span>
                                </div>

                                <div class="product-detail">
                                    <h4>Product Details :</h4>
                                    <p>{{i.short}}</p>
                                </div>

                                <ul class="brand-list">
                                    <li>
                                        <div class="brand-box">
                                            <h5>Brand Name:</h5>
                                            {% if i.brand is not None %}
                                            <h6>{{i.brand}}</h6>
                                            {% endif %}
                                        </div>
                                    </li>

                                    <li>
                                        <div class="brand-box">
                                            <h5>Product Code:</h5>
                                            <h6>{{i.ref}}</h6>
                                        </div>
                                    </li>

                                    <li>
                                        <div class="brand-box">
                                            <h5>Product Type:</h5>
                                            <h6>{{i.category}}</h6>
                                        </div>
                                    </li>
                                </ul>
                                <div class="select-size">
                                    <h4>Color :</h4>
                                    <button class="btn btn-sm choose-color" data-color="{{color.colour__id}}" value="{{color.colour__title}}" style="background-color: 
                                        {{i.variation_set.first.color}}"></button>
                                </div>

                                <div class="select-size">
                                    <h4>Check Size :</h4>
                                    <select class="form-select select-form-size">
                                        {% for s in i.variation_set.all %}
                                        <option value="1.2">{{s.size}}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="modal-button">
                                    <button onclick="location.href = '/shop/{{i.category}}/{{i.name|slugify}}-{{i.id}}'"
                                        class="btn btn-md add-cart-button icon">Add
                                        To Cart</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- Quick View Modal Box End -->

 {% for i in related %}
    <div class="modal fade theme-modal view-modal" id="view{{i.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl modal-fullscreen-sm-down">
            <div class="modal-content">
                <div class="modal-header p-0">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <i class="fa-solid fa-xmark"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row g-sm-4 g-2">
                        <div class="col-lg-6">
                            <div class="slider-image">
                                <img style="width: 400px; height: 400px" src="{{i.thumb_nail.url}}" class="img-fluid blur-up lazyload"
                                    alt="">
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="right-sidebar-modal">
                                <h4 class="title-name">{{i.name}}</h4>
                                {% if i.variation_set.first.discount %}
                                <h4 class="price">&#8358;{{i.variation_set.first.dis_price|floatformat:2}}</h4>
                                {% else %}
                                <h4 class="price">&#8358;{{i.variation_set.first.price|floatformat:2}}</h4>
                                {% endif %}
                                <div class="product-rating">
                                    <ul class="rating">
                                        {% for star in p.avg_ratings|ljust:p.avg_ratings %}
                                        <li>
                                            <i data-feather="star" class="fill"></i>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    <span class="ms-2">8 Reviews</span>
                                    <span class="ms-2 text-danger">6 sold in last 16 hours</span>
                                </div>

                                <div class="product-detail">
                                    <h4>Product Details :</h4>
                                    <p>{{i.short}}</p>
                                </div>

                                <ul class="brand-list">
                                    <li>
                                        <div class="brand-box">
                                            <h5>Brand Name:</h5>
                                            {% if i.brand is not None %}
                                            <h6>{{i.brand}}</h6>
                                            {% endif %}
                                        </div>
                                    </li>

                                    <li>
                                        <div class="brand-box">
                                            <h5>Product Code:</h5>
                                            <h6>{{i.ref}}</h6>
                                        </div>
                                    </li>

                                    <li>
                                        <div class="brand-box">
                                            <h5>Product Type:</h5>
                                            <h6>{{i.category}}</h6>
                                        </div>
                                    </li>
                                </ul>
                                <div class="select-size">
                                    <h4>Color :</h4>
                                    <button class="btn btn-sm choose-color" data-color="{{color.colour__id}}" value="{{color.colour__title}}" style="background-color: 
                                        {{i.variation_set.first.color}}"></button>
                                </div>

                                <div class="select-size">
                                    <h4>Cake Size :</h4>
                                    <select class="form-select select-form-size">
                                        <option selected>Select Size</option>
                                        <option value="1.2">1/2 KG</option>
                                        <option value="0">1 KG</option>
                                        <option value="1.5">1/5 KG</option>
                                        <option value="red">Red Roses</option>
                                        <option value="pink">With Pink Roses</option>
                                    </select>
                                </div>

                                <div class="modal-button">
                                    <button onclick="location.href = '/shop/{{i.category}}/{{i.name|slugify}}-{{i.id}}'';"
                                        class="btn btn-md add-cart-button icon">Add
                                        To Cart</button>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}    