cart/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('add-to-cart/', views.add_to_cart, name="add_to_cart"),
    path('delete-from-cart/', views.delete_cart_item, name="delete-from-cart"),
    path('update-cart/', views.update_cart_item, name="update-cart"),
    path('cart', views.cart_list, name="cart"),  
    path('checkout', views.checkout, name="checkout"),  

    path('checkout/payment/success', views.pay_success, name="pay-success"),   


    path('add-wishlist',views.add_wishlist, name='add_wishlist'),
    path('account/dashboard/wishlist',views.wishlist, name='wishlist'),

    path('delivery_price',views.delivery_price, name='delivery'),


] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls import handler400, handler403, handler404, handler500
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *


sitemaps = {
    'products':ProductSitemap,
    'cats': CategorySitemap,
    'vend': VendorSitemap,
    'subcats': SubCategorySitemap,
}


urlpatterns = [
    path('', views.home, name="home"),
    path('shop', views.shop, name="shop"),
    path('search', views.search, name="search"),

    path('shop/<str:title>-<int:cat_id>', views.category_product_list, name="category"),
    
    path('shop/<str:title>', views.subcat_product_list, name="subcat"),

    path('accounts/register', views.registerUser, name="register"),
    path('accounts/login/', views.loginView, name="login"),
    path('accounts/logout', views.logoutUser, name="logout"),
    path('accounts/dashboard', views.user_dash, name="user-dashboard"),
    path('contact-us', views.contact, name="contact"),
    path('about-us', views.about_us, name="about"),
    path('faq', views.faq, name="faq"),
    path('order-tracking', views.order_tracking, name="order-tracking"),

    path('accounts/forgot-password',views.forgot_password, name='forgot-password'),
    path('accounts/reset-password/<token>/',views.reset_password, name='reset-password'),
    path('accounts/change-password', views.change_password, name='change-password'),
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    
] 

handler404 = 'main.views.handler404'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/admin/admin/030/', admin.site.urls),
    path('', include('main.urls')),
    path('shop/', include('product.urls')),
    path('', include('cart.urls')),
    path('payment/', include('paystackpay.urls')),
    path('vendor/', include('vendor.urls')),

    path('www.excelcart.com.ng', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('www.excelcart.org', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('www.excelcart.com', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('www.excelcart.net', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('www.excelcart.shop', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('excelcart.shop', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
    path('excelcart.com', RedirectView.as_view(url='excelcart.com.ng/', permanent=True)),
]

cart/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.timezone import now
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from product.models import *
from main.manager import *

# Create your models here.


class CouponCode(models.Model):
	code = models.CharField(max_length=200, null=True)
	per_off = models.PositiveIntegerField(blank=True, null=True)
	expiry_date = models.DateTimeField(default=now, editable=True)

	def __str__(self): 
		return self.code

class UsedCoupon(models.Model):
    user = models.CharField(max_length=200, null=True)
    code = models.CharField(max_length=200, null=True)
    date = models.DateTimeField(default=now, editable=True)

    def __str__(self): 
        return self.user         
               
class CustomerAddress(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    city = models.CharField(max_length=200, null=True)
    address=models.TextField()
    phone =models.CharField(max_length=15)
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural='address'    

    def __str__(self): 
        return self.name             

# Order
status_choice=(
        ('process','In Process'),
        ('delivered','Delivered'),
    )
class CartOrder(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    code = models.CharField(max_length=100, null=True, blank=True)
    total_amt=models.FloatField()
    discount= models.IntegerField(default=0, null=True, blank=True)
    delivery= models.IntegerField(default=0, null=True, blank=True)
    total = models.IntegerField(default=0, null=True, blank=True)
    paid_status=models.BooleanField(default=False)    
    order_status=models.CharField(choices=status_choice,default='process',max_length=150)
    order_dt=models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name_plural='Orders'

    def save(self, *args, **kwargs) -> None: 
        if self.code == None:    
            self.code = secrets.token_urlsafe(5)                 
            super().save(*args, **kwargs) 
        elif self.order_status == 'delivered':
            order_delivered(self) 
            super().save(*args, **kwargs)     

        else:
            super().save(*args, **kwargs)    

# OrderItems
class CartOrderItems(models.Model):
    order=models.ForeignKey(CartOrder,on_delete=models.CASCADE)
    invoice_no=models.CharField(max_length=150)
    item=models.CharField(max_length=150)
    ref=models.CharField(max_length=150, null=True)
    vendor=models.CharField(max_length=150, null=True)
    image=models.ImageField(upload_to="order/", null=True)
    size=models.CharField(max_length=200)
    color=models.CharField(max_length=200)
    qty=models.IntegerField()
    price=models.FloatField()
    total=models.FloatField()

    class Meta:
        verbose_name_plural='Order Items'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image))

class Wishlist(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='Wishlist'		


class Tracking(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    Ordercode = models.CharField(max_length= 500)

    def __str__(self):
        return self.Ordercode

paystackpay/models.py
from django.db import models
from cart.models import *
from vendor.models import *
from .paystack import PayStack

# Create your models here.

PAYMENT_OPTIONS=(('Cash','Cash On Delivery'),('Transfer','Direct Bank Transfer'),('Paystack','Pay Online [Secured]'))       
        
class Payment(models.Model):
    ref = models.CharField(max_length=21, null=True, blank=True)
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE, null=True)
    order_note = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    customer = models.CharField(max_length=300, null=True, blank=True)
    address = models.ForeignKey(CustomerAddress,on_delete=models.CASCADE)
    amount= models.CharField(max_length=100)
    discount= models.CharField(max_length = 100, null=True, blank=True)
    payment_option= models.TextField(choices=PAYMENT_OPTIONS, default='Cash')
    date_created = models.DateTimeField(default=now)
    date_expected= models.DateTimeField(default=now, editable=True, null=True)
    verified = models.BooleanField(default=False, null=True)

    

    class Meta:
        verbose_name_plural='Payment'

    def __str__(self):
        return self.amount

    def save(self, *args, **kwargs) -> None:
        while not self.ref:
            ref = secrets.token_urlsafe(15)
            object_with_similar_ref = Payment.objects.filter(ref=ref)
            if not object_with_similar_ref:
                self.ref = ref
        if self.verified == True:
            items = CartOrderItems.objects.filter(order = self.order)
            for i in items:
                wallet = VendorWallet.objects.get(vendor__name = i.vendor)
                wallet.balance = int(wallet.balance) + int(i.total)
                wallet.save()               
                    
        super().save(*args, **kwargs)
        
    def amount_value(self) -> int:
        return self.amount *100 

    def verify_payment(self):
        paystack = PayStack()
        status, result = paystack.verify_payment(self.ref, self.amount)
        if status:
            if result["amount"] / 100 == self.amount:
                self.verified = True
            self.save()
        if self.verified:
            return True
        return False

        

product/models.py
from django.db import models
from colorfield.fields import ColorField
from main.models import *
from vendor.models import *
from ckeditor.fields import RichTextField
from django.utils.timezone import now
from django.utils.html import mark_safe
import secrets
from gdstorage.storage import GoogleDriveStorage

# Define Google Drive Storage
gd_storage = GoogleDriveStorage()

# Create your models here.

stock_status =(
        ('1','In Stock'),
        ('2','Out Of Stock'),
        ('3','Pre-order'),
    )

class Product(models.Model):
        vendor = models.ForeignKey(Vendor,on_delete=models.CASCADE, null=True)
        name=models.CharField(max_length=200)
        thumb_nail = models.ImageField(upload_to="product_img/", null=True, storage=gd_storage)
        short = models.CharField(max_length=100, null=True)
        category=models.ForeignKey(Category,on_delete=models.CASCADE, null=True)
        sub_category=models.ForeignKey(SubCategory,on_delete=models.CASCADE, null=True)	
        color = models.CharField(max_length=100, null=True, blank=True)
        brand = models.CharField(max_length=100, null=True, blank=True)
        number=models.PositiveIntegerField(default=1, null=True, blank=True)
        ref=models.CharField(max_length=100, null=True, blank = True)
        description=models.TextField()
        date=models.DateTimeField(default=now)
        new=models.BooleanField(default=False)
        top_deals=models.BooleanField(default=False)
        sales = models.IntegerField(default=0)
        avg_ratings = models.IntegerField(default=0)
        topic_views = models.IntegerField(default=0)
        approve = models.BooleanField(default=False)

        class Meta:
                verbose_name_plural='Product'

        def __str__(self): 
            return self.name    

        def get_absolute_url(self):
            return f'/shop/{self.category}/{self.name}-{self.id}'    

        def save(self, *args, **kwargs) -> None: 
            if self.ref == None:       
                self.ref = secrets.token_urlsafe(7) 
                super().save(*args, **kwargs)  
            else:     
                super().save(*args, **kwargs)

class ProductImage(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    image = models.FileField(upload_to="product_img/", storage=gd_storage)

    class Meta:
        verbose_name_plural='Product Image'

    def __str__(self): 
        return self.product.name #

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))    

SIZE = [
        ("KG", "kilogramme", ),
        ("G", "gramme", ),
        ("XL", "extra-large", ),
    ]

class Variation(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    stock_status = models.CharField(choices=stock_status,default='In Stock',max_length=150)
    size_par = models.CharField(choices=SIZE,default='kilogramme',max_length=150, blank=True, null=True)
    size=models.CharField(max_length=100, null=True)
    price=models.PositiveIntegerField(default=0, null=True)
    dis_price=models.PositiveIntegerField(default=0, null=True, blank=True)
    discount=models.IntegerField(null=True, blank=True)

    class Meta:
    	verbose_name_plural='Variations'

    def __str__(self):
        return self.product.name

    def save(self, *args, **kwargs) -> None: 
        if self.dis_price == 0:
            super().save(*args, **kwargs)
        else:    
            discount = int(self.price) - int(self.dis_price)
            self.discount = discount * 100/int(self.price)
            super().save(*args, **kwargs) 

class ProductInformation(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    manufacturer=models.CharField(max_length=100, null=True, blank = True)
    ingredients = models.CharField(max_length=300, null=True, blank = True)
    package = models.CharField(max_length=300, null=True, blank=True)
    item_number=models.CharField(max_length=300, null=True, blank=True)
    prod_date=models.DateTimeField(default=now, editable=True, blank=True)
    expiry_date=models.DateTimeField(default=now, editable=True, blank=True)

    class Meta:
        verbose_name_plural='Product Info'

    def __str__(self):
        return self.product.name

class ProductCare(models.Model):
        product=models.ForeignKey(Product,on_delete=models.CASCADE)
        care = models.CharField(max_length=500, null=True)

        class Meta:
                verbose_name_plural='Product care'

        def __str__(self):
                return self.product.name


RATING=(
    ("1",'1 Star'),
    ("2",'2 Stars'),
    ("3",'3 Stars'),
    ("4",'4 Stars'),
    ("5",'5 Stars'),
)
class Review(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)    
    product = models.ForeignKey(Product,on_delete=models.CASCADE)   
    text=models.TextField()
    rating=models.IntegerField(choices=RATING,default=1)
    date=models.DateTimeField(default=now)

    class Meta:
        verbose_name_plural='Reviews'

    def get_review_rating(self):
        return self.product               

main/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django import forms
from .models import *
from cart.models import *


class SignupForm(UserCreationForm):
	password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'id': 'password1'}))
	
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["username"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"username",
			'id':"username",
			'placeholder':"Choose a username",
			'autocomplete': "username"

			})
		self.fields["email"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"email", 
			'name':"email",
			'id':"email",
			'placeholder':"Email",
			'autocomplete': "email"
			})
		self.fields["password1"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"password1",
			'id':"password1",
			'placeholder':"Password",
			'autocomplete': "password"
			})
		self.fields["password2"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"password2",
			'id':"password2",
			'placeholder':"Confirm Password",
			'autocomplete': "confirm-password"
			})


	class Meta:
		model=User
		fields=('email','username','password1','password2')


class AddressForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["address"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"address",
			'id':"address",
			'placeholder':"Enter Address",
			'rows': 4,
			})
		self.fields["phone"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"number", 
			'name':"phone",
			'id':"phone",
			'placeholder':"Enter Phone Number"
			})
		self.fields["name"].widget.attrs.update({
			'required':'',
			'class':"form-control",
			'type':"text", 
			'name':"name",
			'id':"name",
			'placeholder':"Enter the name of place"
			})

	class Meta:
		model= CustomerAddress
		fields=('address','phone','name')

main/templates/order-tracked.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
    <title>Tracked Order</title>
{% endblock %}

{% block meta %}
    <meta name="description" property="og:description" content="At Excelcart, we believe in providing our customers with complete transparency. Our order tracking page lets youu follow your packages journey from our warehouse/store to your front-door. Vist today to track your">    
    <meta name="keywords" content="Order tracking, Track my order, Check order status, Order status updates, Shipping status, Package tracking, Delivery tracking, Track shipment, Oder History, View order details, Order confirmation, Track delivery, Find my order">
    <meta name="author" content="Emmanuel Excellent">
    <meta property="og:url" content="https://excelcart.com.ng/order-tracking">
    <meta property="og:title" content="Excelcart No.1 Online Shopping Website">
    <meta property="og:image" content="">
    <meta property="og:image:alt" content="Excelcart Graphics">

    <meta property="twitter:image" content="">
    <meta property="twitter:image:alt" content="Excelcart Graphics">
    <meta property="twitter:card" content="excelcart">
    <meta property="twitter:site" content="@Excelcart">

{% endblock %}

{% block content %}

    <!-- Breadcrumb Section Start -->
    <section class="breadscrumb-section pt-0">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="breadscrumb-contain">
                        <h2>Order Tracking</h2>
                        <nav>
                            <ol class="breadcrumb mb-0">
                                <li class="breadcrumb-item">
                                    <a href="{% url 'home' %}">
                                        <i class="fa-solid fa-house"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">Order Tracking</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Order Detail Section Start -->
    <section class="order-detail">
        <div class="container-fluid-lg">
            <div class="row g-sm-4 g-3">
                    {% for ord in order %}
                <div class="col-xxl-3 col-xl-4 col-lg-6">
                    <div class="order-image">
                        <img src="/media/{{ord.cartorderitems_set.first.image}}" class="img-fluid blur-up lazyload" alt="">
                    </div>
                </div>

                <div class="col-xxl-9 col-xl-8 col-lg-6">
                    <div class="row g-sm-4 g-3">
                        <div class="col-xl-4 col-sm-6">
                            <div class="order-details-contain">
                                <div class="order-tracking-icon">
                                    <i data-feather="package" class="text-content"></i>
                                </div>

                                <div class="order-details-name">
                                    <h5 class="text-content">Order Code</h5>                                    
                                    <h2 class="theme-color">{{ord.code}}</h2>
                                    
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-4 col-sm-6">
                            <div class="order-details-contain">
                                <div class="order-tracking-icon">
                                    <i data-feather="truck" class="text-content"></i>
                                </div>

                                <div class="order-details-name">
                                    <h5 class="text-content">Service</h5>
                                    
                                    <h2>EXCEL</h2>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-4 col-sm-6">
                            <div class="order-details-contain">
                                <div class="order-tracking-icon">
                                    <i class="text-content" data-feather="crosshair"></i>
                                </div>

                                <div class="order-details-name">
                                    <h5 class="text-content">From</h5>
                                    <h4>Excelcart Ibogun</h4>
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-4 col-sm-6">
                            <div class="order-details-contain">
                                <div class="order-tracking-icon">
                                    <i class="text-content" data-feather="map-pin"></i>
                                </div>

                                <div class="order-details-name">
                                    <h5 class="text-content">Destination</h5>
                                    <h4>{{ord.payment_set.first.address.address}}</h4>
                                </div>
                            </div>
                        </div>
                        

                        <div class="col-12 overflow-hidden">
                            <ol class="progtrckr">
                                <li class="progtrckr-done">
                                    <h5>Order Placed</h5>
                                    <h6>{{ord.order_dt|timesince}} ago</h6>
                                </li>
                                <li class="progtrckr-done">
                                    <h5>Order Processing</h5>
                                </li>
                                {% if ord.order_status == 'process' %}
                                <li class="progtrckr-todo">
                                    <h5>Delivered</h5>
                                    <h6>Pending</h6>
                                </li>
                                {% else %}
                                <li class="progtrckr-done">
                                    <h5>Delivered</h5>
                                    <h6>Success</h6>
                                </li>
                                {% endif %}
                            </ol>
                        </div>
                        
                    </div>
                </div>
                    {% endfor %}
            </div>
        </div>
    </section>
    <!-- Order Detail Section End -->
{% endblock content %}

main/templates/order-tracking.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
    <title>Track Order</title>
{% endblock %}

{% block meta %}
    <meta name="description" property="og:description" content="At Excelcart, we believe in providing our customers with complete transparency. Our order tracking page lets youu follow your packages journey from our warehouse/store to your front-door. Vist today to track your">    
    <meta name="keywords" content="Order tracking, Track my order, Check order status, Order status updates, Shipping status, Package tracking, Delivery tracking, Track shipment, Oder History, View order details, Order confirmation, Track delivery, Find my order">
    <meta name="author" content="Emmanuel Excellent">
    <meta property="og:url" content="https://excelcart.com.ng/order-tracking">
    <meta property="og:title" content="Excelcart No.1 Online Shopping Website">
    <meta property="og:image" content="">
    <meta property="og:image:alt" content="Excelcart Graphics">

    <meta property="twitter:image" content="">
    <meta property="twitter:image:alt" content="Excelcart Graphics">
    <meta property="twitter:card" content="excelcart">
    <meta property="twitter:site" content="@Excelcart">

{% endblock %}

{% block content %}


    <!-- Breadcrumb Section Start -->
    <section class="breadscrumb-section pt-0">
        <div class="container-fluid-lg">
            <div class="row">
                <div class="col-12">
                    <div class="breadscrumb-contain">
                        <nav>
                            <ol class="breadcrumb mb-0">
                                <li class="breadcrumb-item">
                                    <a href="{% url 'home' %}">
                                        <i class="fa-solid fa-house"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">Order Tracking</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

   <!-- log in section start -->
    <section class="log-in-section background-image-2 section-b-space">
        <div class="container-fluid-lg w-100">
            <div class="row">
                <div class="col-xxl-6 col-xl-5 col-lg-6 col-sm-8 ms-auto">
                    <div class="image-contain">
                        <img src="{% static 'assets/' %}images/inner-page/dashboard-profile.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-xxl-4 col-xl-5 col-lg-6 col-sm-8 mx-auto">
                    <div class="log-in-box">
                        <div class="log-in-title">
                            <h4>Track Your Order</h4>
                            {% if messages %}
                            {% for message in messages %}
                            <h5 style="color:orangered; font-size: 14;">{{ message }}</h5>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <div class="input-box">
                            <form method="post" class="row g-4">
                                {% csrf_token %}
                                <div class="col-12">                                    
                                    <div class="form-floating theme-form-floating log-in-form">
                                        <input name="order-code" type="text" class="form-control" id="order-code">
                                        <label for="order-code">Order Code</label>
                                    </div>
                                    <i class="theme-color">Go to <a href="{% url 'user-dashboard' %}">DASHBOARD</a> and copy the OrderID of the order you want to track...</i>
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-animation w-100 justify-content-center" type="submit">Track Order</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- log in section end -->

{% endblock content %}